# Generated by Django 5.1.4 on 2024-12-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarnama_app', '0002_alter_product_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
