# Generated by Django 5.1.4 on 2024-12-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarnama_app', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itinery',
            field=models.CharField(default='null', max_length=1000, verbose_name='itinery'),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.CharField(default='null', max_length=100, verbose_name='notes'),
        ),
    ]
