# Generated by Django 5.1.4 on 2024-12-20 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarnama_app', '0004_product_itinery_product_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(verbose_name='Day Number')),
                ('activities', models.TextField(verbose_name='Activities for the Day')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='safarnama_app.product')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('product', 'day')},
            },
        ),
    ]
